services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - 5678:5678
    environment:
      - N8N_SECURE_COOKIE=false
    volumes:
      - /storage/secondary/n8n/data:/home/node/.n8n:z
      - /storage/secondary/n8n/:/files:z
networks: {}
x-dockge:
  urls:
    - ""