---
services:
  opencloud:
    image: ${OC_DOCKER_IMAGE:-opencloudeu/opencloud-rolling}:${OC_DOCKER_TAG:-latest}
    environment:
      - OC_URL=${OC_URL}
      - OCIS_JWT_SECRET=${OCIS_JWT_SECRET}
      - IDM_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
      - OC_LOG_LEVEL=${LOG_LEVEL}
      - OC_LOG_COLOR=${LOG_PRETTY}
      - OC_LOG_PRETTY=${LOG_PRETTY}
      - PROXY_TLS=false
      - OC_ADD_RUN_SERVICES=${START_ADDITIONAL_SERVICES}
      - OC_INSECURE=${INSECURE:-true}
      - PROXY_ENABLE_BASIC_AUTH=${PROXY_ENABLE_BASIC_AUTH:-false}
      - IDM_CREATE_DEMO_USERS=${DEMO_USERS:-false}
      - NOTIFICATIONS_SMTP_HOST=${SMTP_HOST}
      - NOTIFICATIONS_SMTP_PORT=${SMTP_PORT}
      - NOTIFICATIONS_SMTP_SENDER=${SMTP_SENDER:-OpenCloud Notifications <notifications@cloud.opencloud.test>}
      - NOTIFICATIONS_SMTP_USERNAME=${SMTP_USERNAME}
      - NOTIFICATIONS_SMTP_PASSWORD=${SMTP_PASSWORD}
      - NOTIFICATIONS_SMTP_INSECURE=${SMTP_INSECURE}
      - NOTIFICATIONS_SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
      - NOTIFICATIONS_SMTP_ENCRYPTION=${SMTP_TRANSPORT_ENCRYPTION:-none}
      - FRONTEND_ARCHIVER_MAX_SIZE=10000000000
      - PROXY_CSP_CONFIG_FILE_LOCATION=/etc/opencloud/csp.yaml
      - OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST=banned-password-list.txt
      - OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD=${OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD:-true}
      - OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD=${OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD:-true}
      - OC_PASSWORD_POLICY_DISABLED=${OC_PASSWORD_POLICY_DISABLED:-false}
      - OC_PASSWORD_POLICY_MIN_CHARACTERS=${OC_PASSWORD_POLICY_MIN_CHARACTERS:-8}
      - OC_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS=${OC_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS:-1}
      - OC_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS=${OC_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS:-1}
      - OC_PASSWORD_POLICY_MIN_DIGITS=${OC_PASSWORD_POLICY_MIN_DIGITS:-1}
      - OC_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS=${OC_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS:-1}
    volumes:
      - ${OC_CONFIG_DIR}:/etc/opencloud:z
      - ${OC_DATA_DIR}:/var/lib/opencloud:z
      - ./opencloud/secondary/opencloud/banned-password-list.txt:/etc/opencloud/banned-password-list.txt:z
    restart: always
    networks:
      - opencloud-net
    expose:
      - "9200"

volumes:
  opencloud-config:
  opencloud-data:

networks:
  opencloud-net:
